In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("HRData.csv")
df

,EmployeeID,EmployeeName,Salary,Position,State,DateOfBirth,Gender,MaritalStatus,HiringDate,TerminationDate,EmploymentStatus,Department,RecruitmentSource,PerformanceScore,EngagementSurvey,EmployeeSatisfaction
0,1,John Smith,62506,Production Technician I,MA,07/10/83,M,Single,7/5/2011,NaN,Active,Production,LinkedIn,Exceeds,4.60,5
1,2,Sarah Johnson,104437,Sr. DBA,MA,05/05/75,M,Married,3/30/2015,6/16/2016,Voluntarily Terminated,IT/IS,Indeed,Fully Meets,4.96,3
2,3,Michael Williams,64955,Production Technician II,MA,09/19/88,F,Married,7/5/2011,9/24/2012,Voluntarily Terminated,Production,LinkedIn,Fully Meets,3.02,3
3,4,Emily Brown,64991,Production Technician I,MA,09/27/88,F,Married,1/7/2008,NaN,Active,Production,Indeed,Fully Meets,4.84,5
4,5,David Jones,50825,Production Technician I,MA,09/08/89,F,Divorced,7/11/2011,9/6/2016,Voluntarily Terminated,Production,Google Search,Fully Meets,5.00,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,Nana Asare,65893,Production Technician II,MA,05/11/85,M,Single,7/7/2014,NaN,Active,Production,LinkedIn,Fully Meets,4.07,4
307,308,Yaa Yeboah,48513,Production Technician I,MA,05/04/82,F,Single,9/2/2008,9/29/2015,Voluntarily Terminated,Production,Google Search,PIP,3.20,2
308,309,Kojo Ofori,220450,CIO,MA,08/30/79,F,Single,4/10/2010,NaN,Active,IT/IS,Employee Referral,Exceeds,4.60,5
309,310,Esi Amoako,89292,Data Analyst,MA,02/24/79,F,Single,3/30/2015,NaN,Active,IT/IS,Employee Referral,Fully Meets,5.00,3
310,311,Kweku Annan,45046,Production Technician I,MA,08/17/78,F,Widowed,9/29/2014,NaN,Active,Production,LinkedIn,Fully Meets,4.50,5

In [4]:
df.describe()

       EmployeeID         Salary  EngagementSurvey  EmployeeSatisfaction
count  311.000000     311.000000        311.000000            311.000000
mean   156.000000   69020.684887          4.110000              3.890675
std     89.922189   25156.636930          0.789938              0.909241
min      1.000000   45046.000000          1.120000              1.000000
25%     78.500000   55501.500000          3.690000              3.000000
50%    156.000000   62810.000000          4.280000              4.000000
75%    233.500000   72036.000000          4.700000              5.000000
max    311.000000  250000.000000          5.000000              5.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   EmployeeID            311 non-null    int64
 1   EmployeeName          311 non-null    object
 2   Salary                311 non-null    int64
 3   Position              311 non-null    object
 4   State                 311 non-null    object
 5   DateOfBirth           311 non-null    object
 6   Gender                311 non-null    object
 7   MaritalStatus         311 non-null    object
 8   HiringDate            311 non-null    object
 9   TerminationDate       104 non-null    object
 10  EmploymentStatus      311 non-null    object
 11  Department            311 non-null    object
 12  RecruitmentSource     311 non-null    object
 13  PerformanceScore      311 non-null    object
 14  EngagementSurvey      311 non-null    float64
 15  EmployeeSatisfaction  311 non-null    int64
dtypes: float64(1), int64(3), object(12)
memory usage: 39.0+ KB

In [7]:
df.isnull().sum()

EmployeeID                0
EmployeeName              0
Salary                    0
Position                  0
State                     0
DateOfBirth               0
Gender                    0
MaritalStatus             0
HiringDate                0
TerminationDate         207
EmploymentStatus          0
Department                0
RecruitmentSource         0
PerformanceScore          0
EngagementSurvey          0
EmployeeSatisfaction      0
dtype: int64

In [8]:
df.isnull().mean() * 100

EmployeeID               0.000000
EmployeeName             0.000000
Salary                   0.000000
Position                 0.000000
State                    0.000000
DateOfBirth              0.000000
Gender                   0.000000
MaritalStatus            0.000000
HiringDate               0.000000
TerminationDate         66.559486
EmploymentStatus         0.000000
Department               0.000000
RecruitmentSource        0.000000
PerformanceScore         0.000000
EngagementSurvey         0.000000
EmployeeSatisfaction     0.000000
dtype: float64

In [10]:
df['TerminationDate'].isna().value_counts(normalize=True) * 100

TerminationDate
True     66.559486
False    33.440514
Name: proportion, dtype: float64

In [11]:
df['IsActive'] = df['TerminationDate'].isna()

In [14]:
df['TerminationDate'] = df['TerminationDate'].fillna('Still Employed')

In [15]:
df

,EmployeeID,EmployeeName,Salary,Position,State,DateOfBirth,Gender,MaritalStatus,HiringDate,TerminationDate,EmploymentStatus,Department,RecruitmentSource,PerformanceScore,EngagementSurvey,EmployeeSatisfaction,IsActive
0,1,John Smith,62506,Production Technician I,MA,07/10/83,M,Single,7/5/2011,Still Employed,Active,Production,LinkedIn,Exceeds,4.60,5,True
1,2,Sarah Johnson,104437,Sr. DBA,MA,05/05/75,M,Married,3/30/2015,6/16/2016,Voluntarily Terminated,IT/IS,Indeed,Fully Meets,4.96,3,False
2,3,Michael Williams,64955,Production Technician II,MA,09/19/88,F,Married,7/5/2011,9/24/2012,Voluntarily Terminated,Production,LinkedIn,Fully Meets,3.02,3,False
3,4,Emily Brown,64991,Production Technician I,MA,09/27/88,F,Married,1/7/2008,Still Employed,Active,Production,Indeed,Fully Meets,4.84,5,True
4,5,David Jones,50825,Production Technician I,MA,09/08/89,F,Divorced,7/11/2011,9/6/2016,Voluntarily Terminated,Production,Google Search,Fully Meets,5.00,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,Nana Asare,65893,Production Technician II,MA,05/11/85,M,Single,7/7/2014,Still Employed,Active,Production,LinkedIn,Fully Meets,4.07,4,True
307,308,Yaa Yeboah,48513,Production Technician I,MA,05/04/82,F,Single,9/2/2008,9/29/2015,Voluntarily Terminated,Production,Google Search,PIP,3.20,2,False
308,309,Kojo Ofori,220450,CIO,MA,08/30/79,F,Single,4/10/2010,Still Employed,Active,IT/IS,Employee Referral,Exceeds,4.60,5,True
309,310,Esi Amoako,89292,Data Analyst,MA,02/24/79,F,Single,3/30/2015,Still Employed,Active,IT/IS,Employee Referral,Fully Meets,5.00,3,True
310,311,Kweku Annan,45046,Production Technician I,MA,08/17/78,F,Widowed,9/29/2014,Still Employed,Active,Production,LinkedIn,Fully Meets,4.50,5,True

In [21]:
df["TerminationDate"]

0            NaT
1     2016-06-16
2     2012-09-24
3            NaT
4     2016-09-06
         ...
306          NaT
307   2015-09-29
308          NaT
309          NaT
310          NaT
Name: TerminationDate, Length: 311, dtype: datetime64[ns]

In [26]:
df.drop(columns=['TerminationDate'], inplace=True)

In [27]:
df

,EmployeeID,EmployeeName,Salary,Position,State,DateOfBirth,Gender,MaritalStatus,HiringDate,EmploymentStatus,Department,RecruitmentSource,PerformanceScore,EngagementSurvey,EmployeeSatisfaction,IsActive
0,1,John Smith,62506,Production Technician I,MA,07/10/83,M,Single,7/5/2011,Active,Production,LinkedIn,Exceeds,4.60,5,True
1,2,Sarah Johnson,104437,Sr. DBA,MA,05/05/75,M,Married,3/30/2015,Voluntarily Terminated,IT/IS,Indeed,Fully Meets,4.96,3,False
2,3,Michael Williams,64955,Production Technician II,MA,09/19/88,F,Married,7/5/2011,Voluntarily Terminated,Production,LinkedIn,Fully Meets,3.02,3,False
3,4,Emily Brown,64991,Production Technician I,MA,09/27/88,F,Married,1/7/2008,Active,Production,Indeed,Fully Meets,4.84,5,True
4,5,David Jones,50825,Production Technician I,MA,09/08/89,F,Divorced,7/11/2011,Voluntarily Terminated,Production,Google Search,Fully Meets,5.00,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,Nana Asare,65893,Production Technician II,MA,05/11/85,M,Single,7/7/2014,Active,Production,LinkedIn,Fully Meets,4.07,4,True
307,308,Yaa Yeboah,48513,Production Technician I,MA,05/04/82,F,Single,9/2/2008,Voluntarily Terminated,Production,Google Search,PIP,3.20,2,False
308,309,Kojo Ofori,220450,CIO,MA,08/30/79,F,Single,4/10/2010,Active,IT/IS,Employee Referral,Exceeds,4.60,5,True
309,310,Esi Amoako,89292,Data Analyst,MA,02/24/79,F,Single,3/30/2015,Active,IT/IS,Employee Referral,Fully Meets,5.00,3,True
310,311,Kweku Annan,45046,Production Technician I,MA,08/17/78,F,Widowed,9/29/2014,Active,Production,LinkedIn,Fully Meets,4.50,5,True

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   EmployeeID            311 non-null    int64
 1   EmployeeName          311 non-null    object
 2   Salary                311 non-null    int64
 3   Position              311 non-null    object
 4   State                 311 non-null    object
 5   DateOfBirth           311 non-null    object
 6   Gender                311 non-null    object
 7   MaritalStatus         311 non-null    object
 8   HiringDate            311 non-null    object
 9   EmploymentStatus      311 non-null    object
 10  Department            311 non-null    object
 11  RecruitmentSource     311 non-null    object
 12  PerformanceScore      311 non-null    object
 13  EngagementSurvey      311 non-null    float64
 14  EmployeeSatisfaction  311 non-null    int64
 15  IsActive              311 non-null    bool
dtypes: bool(1), float64(1), int64(3), object(11)
memory usage: 36.9+ KB

In [32]:
df.drop(columns=['IsActive'], inplace=True)

In [34]:
df["EngagementSurvey"] = df["EngagementSurvey"].astype(int)
df

,EmployeeID,EmployeeName,Salary,Position,State,DateOfBirth,Gender,MaritalStatus,HiringDate,EmploymentStatus,Department,RecruitmentSource,PerformanceScore,EngagementSurvey,EmployeeSatisfaction
0,1,John Smith,62506,Production Technician I,MA,07/10/83,M,Single,7/5/2011,Active,Production,LinkedIn,Exceeds,4,5
1,2,Sarah Johnson,104437,Sr. DBA,MA,05/05/75,M,Married,3/30/2015,Voluntarily Terminated,IT/IS,Indeed,Fully Meets,4,3
2,3,Michael Williams,64955,Production Technician II,MA,09/19/88,F,Married,7/5/2011,Voluntarily Terminated,Production,LinkedIn,Fully Meets,3,3
3,4,Emily Brown,64991,Production Technician I,MA,09/27/88,F,Married,1/7/2008,Active,Production,Indeed,Fully Meets,4,5
4,5,David Jones,50825,Production Technician I,MA,09/08/89,F,Divorced,7/11/2011,Voluntarily Terminated,Production,Google Search,Fully Meets,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,Nana Asare,65893,Production Technician II,MA,05/11/85,M,Single,7/7/2014,Active,Production,LinkedIn,Fully Meets,4,4
307,308,Yaa Yeboah,48513,Production Technician I,MA,05/04/82,F,Single,9/2/2008,Voluntarily Terminated,Production,Google Search,PIP,3,2
308,309,Kojo Ofori,220450,CIO,MA,08/30/79,F,Single,4/10/2010,Active,IT/IS,Employee Referral,Exceeds,4,5
309,310,Esi Amoako,89292,Data Analyst,MA,02/24/79,F,Single,3/30/2015,Active,IT/IS,Employee Referral,Fully Meets,5,3
310,311,Kweku Annan,45046,Production Technician I,MA,08/17/78,F,Widowed,9/29/2014,Active,Production,LinkedIn,Fully Meets,4,5

In [35]:
df.head(20)

,EmployeeID,EmployeeName,Salary,Position,State,DateOfBirth,Gender,MaritalStatus,HiringDate,EmploymentStatus,Department,RecruitmentSource,PerformanceScore,EngagementSurvey,EmployeeSatisfaction
0,1,John Smith,62506,Production Technician I,MA,07/10/83,M,Single,7/5/2011,Active,Production,LinkedIn,Exceeds,4,5
1,2,Sarah Johnson,104437,Sr. DBA,MA,05/05/75,M,Married,3/30/2015,Voluntarily Terminated,IT/IS,Indeed,Fully Meets,4,3
2,3,Michael Williams,64955,Production Technician II,MA,09/19/88,F,Married,7/5/2011,Voluntarily Terminated,Production,LinkedIn,Fully Meets,3,3
3,4,Emily Brown,64991,Production Technician I,MA,09/27/88,F,Married,1/7/2008,Active,Production,Indeed,Fully Meets,4,5
4,5,David Jones,50825,Production Technician I,MA,09/08/89,F,Divorced,7/11/2011,Voluntarily Terminated,Production,Google Search,Fully Meets,5,4
5,6,Jessica Davis,57568,Production Technician I,MA,05/22/77,F,Single,1/9/2012,Active,Production,LinkedIn,Exceeds,5,5
6,7,Christopher Miller,95660,Software Engineer,MA,05/24/79,F,Single,11/10/2014,Active,Engineering,LinkedIn,Fully Meets,3,3
7,8,Ashley Wilson,59365,Production Technician I,MA,02/18/83,M,Widowed,9/30/2013,Active,Production,Employee Referral,Fully Meets,5,4
8,9,Matthew Anderson,47837,Production Technician I,MA,02/11/70,F,Single,7/6/2009,Active,Production,Diversity Job Fair,Fully Meets,4,3
9,10,Samantha Taylor,50178,IT Support,MA,01/07/88,M,Divorced,1/5/2015,Active,IT/IS,Indeed,Fully Meets,5,5
10,11,Daniel Martinez,54670,Production Technician I,MA,01/12/74,F,Married,1/10/2011,Voluntarily Terminated,Production,Diversity Job Fair,Fully Meets,4,4
11,12,Lauren Thomas,47211,Production Technician I,MA,02/21/74,M,Married,4/2/2012,Voluntarily Terminated,Production,Diversity Job Fair,Fully Meets,4,3
12,13,Andrew Jackson,92328,Data Analyst,TX,07/04/88,M,Divorced,11/10/2014,Active,IT/IS,Diversity Job Fair,Exceeds,4,4
13,14,Elizabeth Thompson,58709,Production Technician I,MA,07/20/83,M,Single,2/20/2012,Active,Production,Google Search,Fully Meets,4,4
14,15,Ryan Lee,52505,Production Technician I,MA,07/15/77,M,Divorced,9/24/2012,Voluntarily Terminated,Production,On-line Web application,Fully Meets,5,5
15,16,Olivia Davis,57834,Production Technician I,MA,10/18/81,M,Single,2/21/2011,Terminated for Cause,Production,Google Search,Fully Meets,5,4
16,17,James Taylor,70131,Production Technician II,MA,04/17/66,F,Married,7/21/2016,Active,Production,Employee Referral,Exceeds,4,3
17,18,Amanda White,59026,Production Technician I,MA,10/27/70,F,Single,4/4/2011,Active,Production,Google Search,Fully Meets,5,5
18,19,Joshua Anderson,110000,Database Administrator,MA,04/04/86,F,Single,7/7/2014,Terminated for Cause,IT/IS,Google Search,Fully Meets,4,4
19,20,Stephanie Martinez,53250,Production Technician I,MA,04/06/79,M,Single,7/8/2013,Active,Production,LinkedIn,Fully Meets,4,4

In [38]:
df['DateOfBirth'] = pd.to_datetime(df['DateOfBirth'])
df['HiringDate'] = pd.to_datetime(df['HiringDate'])

In [40]:
df.isnull().sum()

EmployeeID              0
EmployeeName            0
Salary                  0
Position                0
State                   0
DateOfBirth             0
Gender                  0
MaritalStatus           0
HiringDate              0
EmploymentStatus        0
Department              0
RecruitmentSource       0
PerformanceScore        0
EngagementSurvey        0
EmployeeSatisfaction    0
dtype: int64

In [42]:
#Average salary by department:
df.groupby('Department')['Salary'].mean()

Department
Admin Offices         71791.888889
Engineering           94989.454545
Executive Office     250000.000000
IT/IS                 97064.640000
Production            59953.545455
Sales                 69061.258065
Name: Salary, dtype: float64

In [44]:
#Active vs Terminated employee count:
df['EmploymentStatus'].value_counts()

EmploymentStatus
Active                    207
Voluntarily Terminated     88
Terminated for Cause       16
Name: count, dtype: int64

In [45]:
#Satisfaction vs Performance relationship:
df.groupby('PerformanceScore')['EmployeeSatisfaction'].mean()

PerformanceScore
Exceeds              4.108108
Fully Meets          3.950617
Needs Improvement    3.611111
PIP                  2.538462
Name: EmployeeSatisfaction, dtype: float64

In [47]:
#Average tenure (years):
df['Tenure'] = (pd.Timestamp.today() - df['HiringDate']).dt.days / 365
df['Tenure'].mean()

np.float64(12.67410474386645)

In [48]:
df.to_csv("empolyees.csv", index=False)